schema_version: 1

context:
  name: fetchez
  version: "0.6.2"
  python_min: "3.12"

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 3b81d7d0355b8d62a79d67503e5aea0d3792f3dc04d593ab7637fd7968563c2d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fetchez = fetchez.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - hatch-vcs
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - requests
    - lxml
    - tqdm
    - shapely
    - pyyaml
    - click

tests:
  - python:
      python_version: "${{ python_min }}.*"
      pip_check: true
      imports:
        - fetchez
  - script:
      - fetchez --help
      - fetchez modules list
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/ciresdem/fetchez
  summary: |
    Fetchez is a lightweight, modular Python library and command-line tool
    designed to discover and download geospatial data from a wide variety of
    public repositories.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matth-love
    - mfisher87
