schema_version: 1

context:
  name: fetchez
  python_min: "3.12"
  version: "0.8.5"
  build_number: 0
  sha256: "70a4c2be47ec130a48cfbfe29b064a12489aa43f00b8888052d23136a0936495"

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: ${{ build_number }}
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fetchez = fetchez.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - hatch-vcs
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - requests
    - lxml
    - tqdm
    - shapely
    - pyyaml
    - click
    - pyproj
    - pyogrio
    - filelock
    - mercantile
    - boto3
    - copernicusmarine

tests:
  - python:
      python_version:
        - "${{ python_min }}.*"
        - "*"
      pip_check: true
      imports:
        - fetchez
  - script:
      - fetchez --help
      - fetchez modules list
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/ciresdem/fetchez
  summary: |
    Fetchez is a lightweight, modular Python library and command-line tool
    designed to discover and download geospatial data from a wide variety of
    public repositories.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matth-love
    - mfisher87
